# Generated by Django 5.2.6 on 2025-09-27 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
