# Generated by Django 5.2.6 on 2025-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lessonattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, help_text="Niveau d'éducation de l'utilisateur", max_length=100, null=True),
        ),
    ]
