# Generated by Django 5.2.6 on 2025-09-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Utilisateur premium'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_quiz_date',
            field=models.DateField(blank=True, help_text='Date du dernier quiz créé', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration du statut premium', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_count_today',
            field=models.IntegerField(default=0, help_text="Nombre de quiz créés aujourd'hui"),
        ),
    ]
