# Generated by Django 5.2.6 on 2025-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_premium_user_last_quiz_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attempts_count_today',
            field=models.IntegerField(default=0, help_text="Nombre de tentatives de quiz aujourd'hui"),
        ),
        migrations.AddField(
            model_name='user',
            name='last_attempt_date',
            field=models.DateField(blank=True, help_text='Date de la dernière tentative', null=True),
        ),
    ]
