# Generated by Django 5.2.6 on 2025-10-01 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_attempts_count_today_user_last_attempt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur propriétaire du document (null pour les invités)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text="Adresse IP de l'invité")),
                ('session_id', models.CharField(help_text='ID de session unique', max_length=100, unique=True)),
                ('documents_created', models.PositiveIntegerField(default=0, help_text='Nombre de documents créés')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la session')),
                ('is_blocked', models.BooleanField(default=False, help_text='Session bloquée (limite atteinte)')),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='accounts_gu_ip_addr_36385c_idx'), models.Index(fields=['session_id'], name='accounts_gu_session_ce6329_idx')],
            },
        ),
    ]
