# Generated by Django 5.2.6 on 2025-10-01 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_lesson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='transferred_at',
            field=models.DateTimeField(blank=True, help_text='Date de transfert vers compte utilisateur', null=True),
        ),
        migrations.AddField(
            model_name='guestsession',
            name='transferred_to_user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur vers lequel la session a été transférée', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='guest_session',
            field=models.ForeignKey(blank=True, help_text='Session invité (pour les utilisateurs non connectés)', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestsession'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur (null pour les invités)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['transferred_to_user'], name='accounts_gu_transfe_ab988f_idx'),
        ),
    ]
