# Generated by Django 5.2.6 on 2025-10-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_guestsession_transferred_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='guest_session',
            field=models.ForeignKey(blank=True, help_text="Session invité (pour les documents d'invités)", null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestsession'),
        ),
    ]
