# Generated by Django 5.2.6 on 2025-10-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_document_guest_session'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guestsession',
            name='accounts_gu_ip_addr_36385c_idx',
        ),
        # Note: La contrainte unique sera ajoutée dans une migration ultérieure après nettoyage des doublons
        migrations.AlterField(
            model_name='guestsession',
            name='ip_address',
            field=models.GenericIPAddressField(help_text="Adresse IP de l'invité (unique)"),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['ip_address'], name='accounts_gu_ip_addr_efb543_idx'),
        ),
    ]
