# Generated by Django 5.2.6 on 2025-10-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20251001_2030'),
    ]

    operations = [
        # Maintenant que les doublons sont nettoyés, on peut ajouter la contrainte unique
        migrations.AlterField(
            model_name='guestsession',
            name='ip_address',
            field=models.GenericIPAddressField(help_text="Adresse IP de l'invité (unique)", unique=True),
        ),
    ]
