# Generated by Django 5.2.6 on 2025-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_stripepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text="Fin de la période courante de l'abonnement", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID du customer Stripe', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text="ID de l'abonnement Stripe", max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_interval',
            field=models.CharField(blank=True, help_text="Intervalle de l'abonnement (monthly/yearly)", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(default='inactive', help_text="Statut de l'abonnement Stripe", max_length=50),
        ),
    ]
