# Generated by Django 5.2.6 on 2025-10-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_current_period_end_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripePayment',
        ),
    ]
