# Generated by Django 5.2.6 on 2025-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_stripepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Abonnement programmé pour être annulé à la fin de la période'),
        ),
        migrations.AddField(
            model_name='user',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text="Date d'annulation de l'abonnement", null=True),
        ),
    ]
