# Generated by Django 5.2.6 on 2025-10-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_cancel_at_period_end_user_canceled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='premium_expires_at',
        ),
    ]
