# Generated by Django 5.2.6 on 2025-10-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_clean_stripe_customer_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID du customer Stripe', max_length=255, null=True),
        ),
    ]
